package com.campuslife.demo;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

public class FileEditor {

	public void startingTemplate() throws IOException {
		FileWriter fileWriter = new FileWriter("CampusLifeGames.txt");
		PrintWriter printWriter = new PrintWriter(fileWriter);
		printWriter.print("$1000 BILL EXCHANGE");
		printWriter.print("3 TRUTHS & A LIE");
		printWriter.print("ADDITION");
		printWriter.print("ALL STRINGS ATTACHED");
		printWriter.print("ALPHABITS");
		printWriter.print("ANIMAL PAIR UP");
		printWriter.print("BAG-O-FOOD RELAY");
		printWriter.print("BALLOON NETBALL");
		printWriter.print("BALLOON SHAVE");
		printWriter.print("BALLOON STOMP");
		printWriter.print("BANANA RAC");
		printWriter.print("BANG");
		printWriter.print("BANG YOUR HEAD!");
		printWriter.print("BATCAVE");
		printWriter.print("BAT SPIN");
		printWriter.print("BEACH RELAY RACE");
		printWriter.print("BEDLUM");
		printWriter.print("BIRDIE ON A PERCH");
		printWriter.print("BLIND GUIDANCE");
		printWriter.print("BOBBING FOR BODY PARTS");
		printWriter.print("MODIFIED TWISTER");
		printWriter.print("BODY PARTS");
		printWriter.print("BROOM BALANCE");
		printWriter.print("BUBBLE GUM SCULPTURE");
		printWriter.print("BUCKERK");
		printWriter.print("BUTT WRESTLING");
		printWriter.print("BUZZ");
		printWriter.print("CAPTURE THE FLAG");
		printWriter.print("CARAMEL ONIONS");
		printWriter.print("CAT AND MOUSE");
		printWriter.print("CATCH AN EGG");
		printWriter.print("CATCH N' CLAP");
		printWriter.print("CHARIOT RACE");
		printWriter.print("CHAIN TAG");
		printWriter.print("CHAIR CHARADES");
		printWriter.print("CHEESEBALL SQUIRT OFF");
		printWriter.print("CHINESE PICTIONAR");
		printWriter.print("CHIVALROUS DUDES");
		printWriter.print("CHOPSTICK RACE");
		printWriter.print("CHRISTMAS CAROL SING OFF");
		printWriter.print("CLOTHING RELAY");
		printWriter.print("CLUMPS");
		printWriter.print("CLUMPS WITH QUESTIONS");
		printWriter.print("COOKIE DECORATING CONTEST");
		printWriter.print("COOL GUY CLU");
		printWriter.print("CORNERS");
		printWriter.print("CRAB SOCCER");
		printWriter.print("CROW’S NEST");
		printWriter.print("DANCE OR DARE");
		printWriter.print("DAYS OF THE WEEK");
		printWriter.print("DECADES");
		printWriter.print("DESTROYERS");
		printWriter.print("DIGITS");
		printWriter.print("DIRECTOR MAKEOVER");
		printWriter.print("DIRTY DIAPER");
		printWriter.print("DOES HOT SAUCE TASTE GOOD ON THAT?");
		printWriter.print("DOLLAR JUMP");
		printWriter.print("DUCT TAPE WRAP");
		printWriter.print("DUKE NUKEMBALL");
		printWriter.print("EGGNOG CHU");
		printWriter.print("EVERYBODY’S IT TAG");
		printWriter.print("EVERYONE WHO");
		printWriter.print("FLAG TAG");
		printWriter.print("FRESH");
		printWriter.print("FRUITCAKE EAT-OFF");
		printWriter.print("GETTING READY FOR SCHOOL");
		printWriter.print("GLOW IN THE DARK GAMES");
		printWriter.print("GUESS WHO");
		printWriter.print("GUZZLE RELAY");
		printWriter.print("HAT KNOCK OFF GAME");
		printWriter.print("HEADS OR TAILS");
		printWriter.print("HEADS OR TAILS (COIN TOSS)");
		printWriter.print("HO-HO SLAM");
		printWriter.print("HOMEMADE LEMONADE");
		printWriter.print("HOW MANY BITES");
		printWriter.print("HUMAN FOOSEBALL");
		printWriter.print("HUMAN PACMAN");
		printWriter.print("HUMAN SORRY");
		printWriter.print("HUMAN WRAP-OFF");
		printWriter.print("INDOOR SCAVENGER HUNT");
		printWriter.print("INVENTIONS");
		printWriter.print("KIX BLOW");
		printWriter.print("KNIGHTS, HORSES, CAVALIER");
		printWriter.print("KNOCKDOWN");
		printWriter.print("LADDER");
		printWriter.print("LIFESAVER STICK");
		printWriter.print("LIQUORICE TOWERS");
		printWriter.print("LUMBERJACK GAME OR WRESTLING MOVE");
		printWriter.print("M&M TRAINING");
		printWriter.print("MARSHMALLOW TOSS");
		printWriter.print("MOM’S KISS");
		printWriter.print("MOST PASSES");
		printWriter.print("MUSICAL BABY FOOD");
		printWriter.print("MUSICAL EAT-OFF");
		printWriter.print("MYSTERY MEAT");
		printWriter.print("NAME THAT TUNE");
		printWriter.print("NASAL SHOOT");
		printWriter.print("ORANGE BOWLS");
		printWriter.print("ORANGE PASS");
		printWriter.print("OUTBURST");
		printWriter.print("PANTYHOSE PUDDING RACE");
		printWriter.print("PAPER HOCKEY");
		printWriter.print("PAPER, ROCK, SCISSORS TAG");
		printWriter.print("PAPER WAR");
		printWriter.print("PAPER WARPENGUIN FOOTBALL");
		printWriter.print("PEPSI CHALLENGE");
		printWriter.print("PERSPECTIVE GAME");
		printWriter.print("PICTIONARY");
		printWriter.print("PIN HEAD");
		printWriter.print("PLEXIGLASS");
		printWriter.print("POOP DEC");
		printWriter.print("POP CHUG");
		printWriter.print("PUMPKIN BOWLING");
		printWriter.print("PUMPKIN DECORATING CONTEST");
		printWriter.print("PUMPKIN PIE EATING CONTEST");
		printWriter.print("PUMPKIN SEED SPITTING CONTEST");
		printWriter.print("PUZZLE RACE");
		printWriter.print("Q-TIP SHOOT");
		printWriter.print("QUARTER DROP");
		printWriter.print("QUESTION GAME");
		printWriter.print("RED ROVER (IN A SQUARE)");
		printWriter.print("REFRIGERATOR BOX RACK");
		printWriter.print("REVERSE CHARADE");
		printWriter.print("SANTA PASS");
		printWriter.print("SHOE RELAY");
		printWriter.print("SHOUT RELAY");
		printWriter.print("SIT DOWN IF");
		printWriter.print("SKATEBOARD PLUNGER RELAY");
		printWriter.print("SLED RACE");
		printWriter.print("SPAGHETTITIONARY");
		printWriter.print("SPEW");
		printWriter.print("STANDUP");
		printWriter.print("STAR WARS");
		printWriter.print("STRAW TOWER");
		printWriter.print("SUPERHER");
		printWriter.print("SURGICAL GLOVE BLOW-UP");
		printWriter.print("SHOOT OFF");
		printWriter.print("SWINGING MARSHMALLOWS");
		printWriter.print("TASTE");
		printWriter.print("THANKSGIVING BABIES");
		printWriter.print("THE GAUNTLET");
		printWriter.print("TOILET PAPER");
		printWriter.print("TOILET TAG");
		printWriter.print("WORLD'S WORST BREAKDANCERSTOSS THE RAG");
		printWriter.print("TOUCH FOOTBALL WITH A MELON");
		printWriter.print("TP SNOWMAN");
		printWriter.print("TRICYCLE RACE");
		printWriter.print("ULTIMATE BANANA");
		printWriter.print("WADDLE TO THE BOTTLE");
		printWriter.print("WARBALZ");
		printWriter.print("WHAT WOULD YOU DO FOR CANDY");
		printWriter.print("WHIP CREAM SHAVE");
		
		printWriter.close();
	}

}
